// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/OICjangirrahul/students/internal/adapters/http"
	"github.com/OICjangirrahul/students/internal/adapters/repositories"
	"github.com/OICjangirrahul/students/internal/config"
	"github.com/OICjangirrahul/students/internal/core/ports"
	"github.com/OICjangirrahul/students/internal/core/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeStudentHandler(cfg *config.Config) (*http.StudentHandler, error) {
	sqLiteRepository, err := repositories.NewSQLiteRepository(cfg)
	if err != nil {
		return nil, err
	}
	studentService := services.NewStudentService(sqLiteRepository)
	studentHandler := http.NewStudentHandler(studentService)
	return studentHandler, nil
}

// wire.go:

var repositorySet = wire.NewSet(repositories.NewSQLiteRepository, wire.Bind(new(ports.StudentRepository), new(*repositories.SQLiteRepository)))
